In [4]:
import leveldb
import sys, numpy as np
sys.path.append("/afs/cs.stanford.edu/u/anenberg/scr/caffe/python/")
import caffe
import lmdb


In [5]:
db = leveldb.LevelDB('/afs/cs.stanford.edu/u/anenberg/scr/CS231N/examples/consecutive/leveldb/train/')

In [2]:
ls ../../CS231/data/allFrames/intermediate_lists/consecutive_5samples_10frames_test_list.txt

ls: cannot access ../../CS231/data/allFrames/intermediate_lists/consecutive_5samples_10frames_test_list.txt: No such file or directory


In [11]:
for i in range(2):
    val = db.Get('%08d'%i)
    datum = caffe.proto.caffe_pb2.Datum()
    datum.ParseFromString(val)
    a = caffe.io.datum_to_array(datum)
    print a[15, 40:50, 40:50]
    print datum.ListFields()[4][1]

[[156 156 156 156 156 156 156 156 160 160]
 [156 156 156 156 156 156 156 156 160 160]
 [156 156 156 156 156 156 156 156 160 160]
 [156 156 156 156 156 156 156 156 160 160]
 [156 156 156 156 156 156 156 156 160 160]
 [156 156 156 156 156 156 156 156 160 160]
 [156 156 156 156 156 156 156 156 160 160]
 [156 156 156 156 156 156 156 156 160 160]
 [154 154 154 154 154 154 154 154 160 160]
 [154 154 154 154 154 154 154 154 160 160]]
87
[[124 124 124 124 124 124 124 124 125 125]
 [124 124 124 124 124 124 124 124 125 125]
 [124 124 124 124 124 124 124 124 125 125]
 [124 124 124 124 124 124 124 124 125 125]
 [124 124 124 124 124 124 124 124 125 125]
 [124 124 124 124 124 124 124 124 125 125]
 [124 124 124 124 124 124 124 124 125 125]
 [124 124 124 124 124 124 124 124 125 125]
 [125 125 125 125 125 125 125 125 124 124]
 [125 125 125 125 125 125 125 125 124 124]]
87


In [30]:
db.close()

AttributeError: 'leveldb.LevelDB' object has no attribute 'close'

In [3]:
!fuser /afs/cs.stanford.edu/u/anenberg/scr/CS231N/examples/consecutive/leveldb/train/LOCK

/afs/cs.stanford.edu/u/anenberg/scr/CS231N/examples/consecutive/leveldb/train/LOCK: 11323


In [4]:
!kill -9 11323